ximport os
from cryptography.fernet import Fernet

def succuss1():
	os.system("echo +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
	os.system("echo              ########## Massage Encrypter And Decrypter ##########")
	os.system("echo +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
	os.system("echo.")
	os.system("echo.")
	os.system("echo +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
	os.system("echo.")
	os.system("echo                     ########## Code By Sacheera ##########")
	os.system("echo.")
	os.system("echo +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
	os.system("echo.")
	os.system("echo.")
	os.system("timeout 03>null")
	os.system("echo --------------------------------------------------------------------------------")
	os.system("echo /                                                                              /")
	os.system("echo /                                                                              /")
	os.system("echo //////////////////////           GENERATE KEY  	    	/////////////////////// ")
	os.system("echo /                                                                              /")
	os.system("echo /                                                                              /")
	os.system("echo --------------------------------------------------------------------------------")	
	os.system("echo.")
	os.system("echo.")
	print("	                                 ----- choose option -----")
	os.system("echo [1]-Go Back")
	os.system("echo [2]-Generate New Key")
	os.system("echo [3]-Exit")
	os.system("timeout 02>null")
	os.system("echo +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
	os.system("echo.")
	os.system("echo.")
	b=input("[+]-Enter What You Want To Do :")
	os.system("echo.")
	os.system("echo.")
	os.system("echo +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
	os.system("timeout 02>null")
	if b=="1":
		os.system("cls")
		os.system("timeout 01>null")
		os.system("echo Please Wait......")
		os.system("cls")
		os.system("timeout 01>null")
		program()
	elif b=="3":
		os.system("exit")

	else:
		os.system("cls")
		os.system("timeout 01>null")
		os.system("echo Please Wait......")
		os.system("cls")
		os.system("timeout 01>null")
		make_key()

def succuss2():
	os.system("echo +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
	os.system("echo             ########## Massage Encrypter And Decrypter ##########")
	os.system("echo +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
	os.system("echo.")
	os.system("echo.")
	os.system("echo +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
	os.system("echo.")
	os.system("echo                     ########## Code By Sacheera ##########")
	os.system("echo.")
	os.system("echo +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
	os.system("echo.")
	os.system("echo.")
	os.system("timeout 03>null")
	os.system("echo --------------------------------------------------------------------------------")
	os.system("echo /                                                                              /")
	os.system("echo /                                                                              /")
	os.system("echo //////////////////////           ENCRYPTER  	    	/////////////////////// ")
	os.system("echo /                                                                              /")
	os.system("echo /                                                                              /")
	os.system("echo --------------------------------------------------------------------------------")	
	os.system("echo.")
	os.system("echo.")
	print("	                                ----- choose option -----")
	os.system("echo [1]-Go Back")
	os.system("echo [2]-Encrypt New File")
	os.system("echo [3]-Exit")
	os.system("timeout 02>null")
	os.system("echo +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
	os.system("echo.")
	os.system("echo.")
	b=input("[+]-Enter What You Want To Do :")
	os.system("echo.")
	os.system("echo.")
	os.system("echo +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
	os.system("timeout 02>null")
	if b=="1":
		os.system("cls")
		os.system("timeout 01>null")
		os.system("echo Please Wait......")
		os.system("cls")
		os.system("timeout 01>null")
		program()

	elif b=="3":
		os.system("exit")

	else:
		os.system("cls")
		os.system("timeout 01>null")
		os.system("echo Please Wait......")
		os.system("cls")
		os.system("timeout 01>null")
		encrypt()



def code():
	os.system("echo +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
	os.system("timeout 01>null")
	os.system("echo              ########## Massage Encrypter And Decrypter ##########")
	os.system("timeout 01>null")
	os.system("echo +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
	os.system("timeout 01>null")
	os.system("echo.")
	os.system("echo.")
	os.system("echo +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
	os.system("timeout 01>null")
	os.system("echo.")
	os.system("echo                      ########## Code By Sacheera ##########")
	os.system("timeout 01>null")
	os.system("echo.")
	os.system("echo +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
	os.system("timeout 01>null")
	os.system("echo.")
	os.system("timeout 01>null")
	os.system("color 03")
	os.system("timeout 01>null")
	os.system("color 04")
	os.system("timeout 01>null")
	os.system("color 05")
	os.system("timeout 01>null")
	os.system("color 06")
	os.system("timeout 01>null")
	os.system("color 07")
	os.system("color 02")
	os.system("timeout 02>null")
	os.system("echo.")
	os.system("echo.")
	os.system("echo.")
	os.system("echo +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
	print("	                              ----- choose option -----")
	os.system("echo.")
	os.system("echo.")
	os.system("echo.")
	os.system("echo [1]-Make New Key File")
	os.system("echo [2]-Encrypt A Massage")
	os.system("echo [3]-Decrypt A Massage")
	os.system("echo [4]-Exit")

	os.system("echo.")
	os.system("echo.")
	os.system("echo.")
	os.system("echo +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
	os.system("timeout 03>null")
	os.system("echo.")
	os.system("echo.")
	global x
	x=input("[+]-Enter What You Want To Do :")
	os.system("echo.")
	os.system("echo.")
	os.system("echo +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
	os.system("timeout 03>null")
	return x





def make_key():
	os.system("echo +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
	os.system("echo              ########## Massage Encrypter And Decrypter ##########")
	os.system("echo +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
	os.system("echo.")
	os.system("echo.")
	os.system("echo +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
	os.system("echo.")
	os.system("echo                       ########## Code By Sacheera ##########")
	os.system("echo.")
	os.system("echo +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
	os.system("echo.")
	os.system("echo.")
	os.system("timeout 03>null")
	os.system("echo --------------------------------------------------------------------------------")
	os.system("echo /                                                                              /")
	os.system("echo /                                                                              /")
	os.system("echo //////////////////////          GENERATE KEY 	    	/////////////////////// ")
	os.system("echo /                                                                              /")
	os.system("echo /                                                                              /")
	os.system("echo --------------------------------------------------------------------------------")
	os.system("timeout 03>null")
	os.system("echo --------------------------------------------------------------------------------")
	os.system("echo.")
	os.system("echo.")
	y=input("[+]-Enter Key Name :")
	os.system("echo.")
	os.system("echo.")
	os.system("echo --------------------------------------------------------------------------------")
	key=Fernet.generate_key()
	file=open(y+".key","wb")
	file.write(key)
	file.close()
	os.system("timeout 03>null")
	os.system("cls")
	os.system("timeout 01>null")
	os.system("echo Generate Succusses")
	os.system("timeout 02>null")
	os.system("cls")
	os.system("timeout 02>null")
	os.system("echo Please Wait......")
	os.system("timeout 03>null")
	os.system("cls")
	os.system("timeout 03>null")
	succuss1()

def encrypt():
	os.system("echo +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
	os.system("echo             ########## Massage Encrypter And Decrypter ##########")
	os.system("echo +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
	os.system("echo.")
	os.system("echo.")
	os.system("echo +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
	os.system("echo.")
	os.system("echo                     ########## Code By Sacheera ##########")
	os.system("echo.")
	os.system("echo +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
	os.system("echo.")
	os.system("echo.")
	os.system("timeout 03>null")

	os.system("echo --------------------------------------------------------------------------------")
	os.system("echo /                                                                              /")
	os.system("echo /                                                                              /")
	os.system("echo //////////////////////           ENCRYPTER  	    	/////////////////////// ")
	os.system("echo /                                                                              /")
	os.system("echo /                                                                              /")
	os.system("echo --------------------------------------------------------------------------------")	
	os.system("echo.")
	os.system("echo.")
	os.system("timeout 03>null")
	os.system("echo --------------------------------------------------------------------------------")
	os.system("echo.")
	os.system("echo.")
	y=input("[+]-Enter Name To Open Key File :")
	os.system("echo.")
	os.system("echo.")
	os.system("echo --------------------------------------------------------------------------------")
	os.system("echo.")
	os.system("echo.")
	os.system("timeout 03>null")
	key=open(y,"rb").read()
	f=Fernet(key)
	msg=input("[+]-Enter Massage That You Want To Encrypt :").encode()
	os.system("echo.")
	os.system("echo.")
	os.system("echo --------------------------------------------------------------------------------")
	os.system("timeout 02>null")
	enc=f.encrypt(msg)
	os.system("echo.")
	os.system("echo.")
	name=input("[+]-Enter File Name To Save :")
	os.system("echo.")
	os.system("echo.")
	os.system("echo --------------------------------------------------------------------------------")
	file3=open(name,"wb")
	file3.write(enc)
	file3.close()
	os.system("timeout 03>null")
	os.system("cls")
	os.system("timeout 01>null")
	os.system("echo Encrypt Succusses")
	os.system("timeout 02>null")
	os.system("cls")
	os.system("timeout 02>null")
	os.system("echo Please Wait......")
	os.system("timeout 03>null")
	os.system("cls")
	os.system("timeout 03>null")
	succuss2()



def decrypt():
	os.system("echo +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
	os.system("echo            ########## Massage Encrypter And Decrypter ##########")
	os.system("echo +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
	os.system("echo.")
	os.system("echo.")
	os.system("echo +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
	os.system("echo.")
	os.system("echo                     ########## Code By Sacheera ##########")
	os.system("echo.")
	os.system("echo +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
	os.system("echo.")
	os.system("echo.")
	os.system("timeout 03>null")
	os.system("echo --------------------------------------------------------------------------------")
	os.system("echo /                                                                              /")
	os.system("echo /                                                                              /")
	os.system("echo //////////////////////           DECRYPTER  	    	/////////////////////// ")
	os.system("echo /                                                                              /")
	os.system("echo /                                                                              /")
	os.system("echo --------------------------------------------------------------------------------")	
	os.system("echo.")
	os.system("echo.")
	os.system("timeout 03>null")
	os.system("echo --------------------------------------------------------------------------------")
	os.system("echo.")
	os.system("echo.")
	y=input("[+]-Enter Name To Open Key File :")
	os.system("echo.")
	os.system("echo.")
	os.system("echo --------------------------------------------------------------------------------")
	os.system("timeout 02>null")
	os.system("echo.")
	os.system("echo.")
	key=open(y,"rb").read()
	f=Fernet(key)

	ss=input("[+]-Enter File Name That You Want To Decrypt :")
	decfile=open(ss,"rb").read()
	global dec
	dec=f.decrypt(decfile)
	os.system("echo.")
	os.system("echo.")
	os.system("echo --------------------------------------------------------------------------------")
	os.system("timeout 03>null")
	os.system("cls")
	os.system("timeout 01>null")
	os.system("echo Decrypt Succusses")
	os.system("timeout 02>null")
	os.system("cls")
	os.system("timeout 02>null")
	os.system("echo Please Wait......")
	os.system("timeout 03>null")
	os.system("cls")
	os.system("timeout 03>null")
	succuss3()


def succuss3():
	os.system("echo +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
	os.system("echo            ########## Massage Encrypter And Decrypter ##########")
	os.system("echo +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
	os.system("echo.")
	os.system("echo.")
	os.system("echo +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
	os.system("echo.")
	os.system("echo                   ########## Code By Sacheera ##########")
	os.system("echo.")
	os.system("echo +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
	os.system("echo.")
	os.system("echo.")
	os.system("timeout 03>null")
	os.system("echo --------------------------------------------------------------------------------")
	os.system("echo /                                                                              /")
	os.system("echo /                                                                              /")
	os.system("echo //////////////////////           DECRYPTER  	    	/////////////////////// ")
	os.system("echo /                                                                              /")
	os.system("echo /                                                                              /")
	os.system("echo --------------------------------------------------------------------------------")	
	os.system("echo.")
	os.system("echo.")
	os.system("echo +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
	print("[+]Massage is ============>>>   ",dec)
	os.system("echo +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
	os.system("echo.")
	os.system("echo.")
	print("                                  ----- choose option -----")
	os.system("echo [1]-Go Back")
	os.system("echo [2]-Decrypt New File")
	os.system("echo [2]-exit")
	os.system("timeout 02>null")
	os.system("echo +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
	os.system("echo.")
	os.system("echo.")
	b=input("[+]-Enter What You Want To Do :")
	os.system("echo.")
	os.system("echo.")
	os.system("echo +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
	os.system("timeout 02>null")
	if b=="1":
		os.system("cls")
		os.system("timeout 01>null")
		os.system("echo Please Wait......")
		os.system("cls")
		os.system("timeout 01>null")
		program()

	elif b=="3":
		os.system("exit")

	else:
		os.system("cls")
		os.system("timeout 01>null")
		os.system("echo Please Wait......")
		os.system("cls")
		os.system("timeout 01>null")
		decrypt()





def program():
	x=code()
	if x=="1":
		os.system("cls")
		make_key()


	elif x=="2":
		os.system("cls")
		encrypt()

	elif x=="4":
		os.system("exit")



	elif x=="3":
		os.system("cls")
		decrypt()

program()
	